name: manger_de_saison
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-83.0.dev <4.0.0'

dependencies:
  dropdown_button2: ^2.3.8
  easy_search_bar: ^2.5.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.3
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#489949"
  image: assets/splash.png
  android_12: 
    image: assets/splash/png
    color: "#489949"

flutter:
  uses-material-design: true
  assets: 
    - assets/pics/
    - assets/calendar.json