name: manger_de_saison
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-83.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts: 
    - family: Khand
      fonts:
        - asset: assets/font/Khand-Light.ttf
          weight: 300
        - asset: assets/font/Khand-Regular.ttf
          weight: 400
        - asset: assets/font/Khand-Medium.ttf
          weight: 500
        - asset: assets/font/Khand-SemiBold.ttf
          weight: 600
        - asset: assets/font/Khand-Bold.ttf
          weight: 700
  assets: 
    - assets/pics/
    - assets/calendar.json